Added first unity cardboard tutorial blog posts
Tengio/tengio.com pull request #2
Opened 2016-09-16 18:19 UTC by quentinleguennec

@luigi-agosti Ready for review. I'm not sure about the naming convention of the files, I will do several posts on the same subject, so maybe I should add them all in a folder. Also not sure about the syntax for the links of the images.

2016-09-17 09:08 UTC, luigi-agosti commented on content/blog/0-introduction.md
> +tags = [ "Unity" "Cardboard" "VR" "tutorial" ]
Tags are comma separated. Remove tutorial

2016-09-17 09:08 UTC, luigi-agosti commented on content/blog/1-pack-up-the-gears-for-your-VR-trip.md
> +
Merge the intro (6) into this (7). Intro doesn't have enough to be one post.

2016-09-17 09:08 UTC, luigi-agosti commented on content/blog/1-pack-up-the-gears-for-your-VR-trip.md
> +tags = [ "Unity" "Cardboard" "VR" "tutorial" ]
same as for 6 remove tutorial and use comma as separator of the array

2016-09-17 09:08 UTC, luigi-agosti commented on content/blog/0-introduction.md
> +author = "Quentin"
put author as lowercase... then check the file /layouts/partials/author.html ad a case for you and put an image of you in /static/images/authors/ ... size should be around 150/150 but I can change it after in case

2016-09-17 09:08 UTC, luigi-agosti commented on content/blog/1-pack-up-the-gears-for-your-VR-trip.md
> +title = "Crossing realities: A VR journey"
"Crossing realities: A VR journey"  ... maybe we can use title like "Crossing realities: A VR journey. Part 1" ... or "Crossing realities: Pack up the gears" and then "Crossing realities: Baby steps into VR"

2016-09-17 09:08 UTC, luigi-agosti commented on content/blog/1-pack-up-the-gears-for-your-VR-trip.md
> +While Unity is installing you can create your compulsory Unity account (https://id.unity.com/account/new).
use part of the text for the link like: [Unity account](https://id.unity.com/account/new)

2016-09-17 09:08 UTC, luigi-agosti commented on content/blog/1-pack-up-the-gears-for-your-VR-trip.md
> +The documentation for the Cardboard API is available on Google developers website (https://developers.google.com/vr/unity/). Follow the instructions on the “Get Started” section (https://developers.g
Integrate links more into the text with [visible words](link)

2016-09-17 09:08 UTC, luigi-agosti commented on content/blog/2-baby-steps-into-vr.md
> +TODO finish it :grin:
no todo it goes live when is finished

2016-09-17 09:08 UTC, luigi-agosti commented on content/blog/2-baby-steps-into-vr.md
> +description = "TODO"
Need some description

2016-09-17 09:08 UTC, luigi-agosti commented on content/blog/0-introduction.md
> +A few months back I started a fantastic journey by diving into Virtual Reality. It happened quite casually, I was peacefully minding my how business when someone putted a VR headset in my hands. I do
business when someone putted (PUT) a VR headset

But I do recall that the first think (THING) I thought was

which also happen (HAPPENED) to be the second and third thinks ( THING) I thought

easy to carry around and still produce(S)

tested Unity about two weeks ago (BEFORE) and

2016-09-17 09:08 UTC, luigi-agosti commented on content/blog/1-pack-up-the-gears-for-your-VR-trip.md
> +While Unity is installing you can create your compulsory Unity account (https://id.unity.com/account/new).
to start developing VR apps is (ARE)

that your model either have (HAS) a

or a hole that let(S)

have any of those which limits (LIMIT)

interactions in game(S)

2016-09-17 09:10 UTC, luigi-agosti commented on content/blog/1-pack-up-the-gears-for-your-VR-trip.md
> +The documentation for the Cardboard API is available on Google developers website (https://developers.google.com/vr/unity/). Follow the instructions on the “Get Started” section (https://developers.g
The first think (THING) you need to do

Once you've got (GONE)

2016-09-17 09:13 UTC, luigi-agosti commented on content/blog/2-baby-steps-into-vr.md
> +
thinks (THINGS) for you (until cardboard

2016-09-17 09:14 UTC, luigi-agosti commented on content/blog/2-baby-steps-into-vr.md
> +
that was automatically create(D) for you

2016-09-17 09:15 UTC, luigi-agosti commented on content/blog/2-baby-steps-into-vr.md
> +Now if we click *Play* we can simulate head movement by holding the “alt” key and moving the mouse. There is also a reticle in the center of our view. But we cannot move yet, and there is nothing to
at unwanted position(S)

2016-09-17 09:17 UTC, luigi-agosti commented on content/blog/2-baby-steps-into-vr.md
> +
LETS

floor by increasing it's (ITS) *Y*

2016-09-17 09:18 UTC, luigi-agosti commented on content/blog/2-baby-steps-into-vr.md
> +
One think (THING)

2016-09-17 09:19 UTC, luigi-agosti commented on content/blog/2-baby-steps-into-vr.md
> +
so you are submitted (SUBJECT) to gravity 
which make(S) it realistic

2016-09-17 09:21 UTC, luigi-agosti commented on content/blog/2-baby-steps-into-vr.md
> +```cs
that you will call (WILL BE CALLED?)

2016-09-17 09:23 UTC, luigi-agosti commented on content/blog/2-baby-steps-into-vr.md
> +When moving around you may notice that it's sometimes hard to see if you are actually moving or not, specially if you can't see the cube. To fix that I often draw a chessboard pattern on the plane us
moving or not, (E)specially

2016-09-17 09:34 UTC, luigi-agosti requested changes

2016-09-20 21:05 UTC, luigi-agosti commented
@quentinleguennec review done have a look if you have time

2016-09-23 12:48 UTC, quentinleguennec commented on content/blog/2-baby-steps-into-vr.md
> +TODO finish it :grin:
The second blog post is not finished yet, I need to add content before it goes live.

2016-09-23 12:54 UTC, quentinleguennec commented on content/blog/2-baby-steps-into-vr.md
> +
This "Let's" is as in "Let us" so the "'s" is right in this specific case.

2016-09-23 13:28 UTC, luigi-agosti commented on content/blog/2-baby-steps-into-vr.md
> +TODO finish it :grin:
ok

2016-09-23 13:28 UTC, luigi-agosti commented on content/blog/2-baby-steps-into-vr.md
> +
ok

2016-09-27 14:55 UTC, VeronicaTam commented on content/blog/1-intro-pack-up-the-gears-for-your-VR-trip.md
> +A few months back I started a fantastic journey by diving into Virtual Reality. It happened quite casually, I was peacefully minding my how business when someone put a VR headset in my hands. I don't
I definitely didn't (stole) STEAL

2016-09-27 14:55 UTC, VeronicaTam commented on content/blog/1-intro-pack-up-the-gears-for-your-VR-trip.md
> +
(in game) IN-GAME

2016-09-27 14:55 UTC, VeronicaTam commented on content/blog/1-intro-pack-up-the-gears-for-your-VR-trip.md
> +Congratulation! Your first VR app is ready to run! Now follow Google's instructions to build it to your device. Once this is done the app should start automatically, place the device in your Cardboar
CONGRATULATIONS

2016-09-27 14:55 UTC, VeronicaTam commented on content/blog/2-baby-steps-into-vr.md
> +
The camera representS your eyes

2016-09-27 14:55 UTC, VeronicaTam commented on content/blog/2-baby-steps-into-vr.md
> +
and there is nothing (NOWHERE?) to move to anyway

2016-09-27 14:55 UTC, VeronicaTam commented on content/blog/2-baby-steps-into-vr.md
> +
so all your in game (IN-GAME)

2016-09-27 14:55 UTC, VeronicaTam commented on content/blog/2-baby-steps-into-vr.md
> +
quick explanation for (OF) the key

2016-09-27 14:55 UTC, VeronicaTam commented on content/blog/2-baby-steps-into-vr.md
> +
And Unity will prevent(s) you

2016-09-27 14:55 UTC, VeronicaTam commented on content/blog/2-baby-steps-into-vr.md
> +
straight forward (straightforward)

2016-09-27 14:55 UTC, VeronicaTam commented on content/blog/2-baby-steps-into-vr.md
> +
move in a(n) direction it 

mid-air

2016-09-27 14:55 UTC, VeronicaTam commented on content/blog/2-baby-steps-into-vr.md
> +
This type of movement is also physics based (physics-based)

2016-09-27 14:55 UTC, VeronicaTam commented on content/blog/2-baby-steps-into-vr.md
> +
replace the auto-generated code by (WITH) this

2016-09-27 14:55 UTC, VeronicaTam commented on content/blog/2-baby-steps-into-vr.md
> +
path **and avoid obstacle(S)**

 that (the) user(S) can look around when moving toward his(THEIR) goal, the disadvantage is that he doesn't (THEY DON'T) have direct

2016-09-27 14:55 UTC, VeronicaTam commented on content/blog/2-baby-steps-into-vr.md
> +
*Player(S)* move around.

computation time if(IS) very critical

2016-09-27 14:55 UTC, VeronicaTam commented on content/blog/2-baby-steps-into-vr.md
> +
Unity will do his (ITS)

2016-09-27 14:55 UTC, VeronicaTam commented on content/blog/2-baby-steps-into-vr.md
> +
you add a(n) new obstacle

2016-09-27 19:38 UTC, merged